name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        TOKEN: ${{secrets.TOKEN}}
      run: |
        curl -X POST -H 'Content-Type: application/json' 'https://deploy.abelab.dev' -d '{"app": "rits_haha", "token": "'"$TOKEN"'"}'
